### ISSUE TITLE
Price List Selection

### ISSUE THREAD

**Issue by yongks** [wifijanitor/GPL#1]
Hi wifijanitor, would like to know any tips on below:
- which region of price list to download, such as China, Asiapac, Jpn. 
- which category: product&services, product only, services to product
- file format: compressed excel, or normal excel

Thanks in advance.

**Comment by wifijanitor** [comment]
This version of the script pulls:
The US Price list
Products and Services as an ascii flat file
output is a csv that is  "|" delimited
